CREATE TABLE job_posting (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    fingerprint         VARCHAR(64)  NOT NULL,
    canonical_url       VARCHAR(1024) NOT NULL,
    title               VARCHAR(512) NOT NULL,
    employer_name       VARCHAR(512),
    employer_org_number VARCHAR(32),
    municipality        VARCHAR(128),
    description         TEXT,
    language            VARCHAR(8),
    ats_vendor          VARCHAR(32)  NOT NULL DEFAULT 'OTHER',
    apply_url           VARCHAR(2048),
    published_at        TIMESTAMPTZ,
    deadline_at         TIMESTAMPTZ,
    status              VARCHAR(32)  NOT NULL DEFAULT 'DISCOVERED',
    first_seen_at       TIMESTAMPTZ  NOT NULL,
    last_seen_at        TIMESTAMPTZ  NOT NULL
);

CREATE TABLE job_posting_source (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    job_posting_id BIGINT       NOT NULL REFERENCES job_posting (id) ON DELETE CASCADE,
    source         VARCHAR(32)  NOT NULL,
    source_ad_id   VARCHAR(256) NOT NULL,
    source_url     VARCHAR(2048),
    raw_payload    JSONB,
    fetched_at     TIMESTAMPTZ  NOT NULL
);

CREATE TABLE ats_tenant (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    vendor           VARCHAR(32)  NOT NULL,
    host             VARCHAR(255) NOT NULL,
    feed_url         VARCHAR(1024) NOT NULL,
    discovered_from  VARCHAR(32)  NOT NULL,
    last_polled_at   TIMESTAMPTZ,
    etag             VARCHAR(255),
    active           BOOLEAN      NOT NULL DEFAULT TRUE,
    failure_count    INTEGER      NOT NULL DEFAULT 0
);

CREATE TABLE search_criteria (
    id                      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name                    VARCHAR(128) NOT NULL,
    query                   VARCHAR(512),
    municipality_codes      TEXT,
    municipality_names      TEXT,
    occupation_field_codes  TEXT,
    enabled                 BOOLEAN      NOT NULL DEFAULT TRUE
);

CREATE TABLE ingest_run (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source       VARCHAR(32)  NOT NULL,
    started_at   TIMESTAMPTZ  NOT NULL,
    finished_at  TIMESTAMPTZ,
    fetched      INTEGER      NOT NULL DEFAULT 0,
    created      INTEGER      NOT NULL DEFAULT 0,
    merged       INTEGER      NOT NULL DEFAULT 0,
    errors       INTEGER      NOT NULL DEFAULT 0,
    status       VARCHAR(32)  NOT NULL,
    message      TEXT
);

CREATE UNIQUE INDEX ux_job_posting_fingerprint       ON job_posting (fingerprint);
CREATE        INDEX ix_job_posting_canonical_url     ON job_posting (canonical_url);
CREATE        INDEX ix_job_posting_published_at      ON job_posting (published_at DESC);
CREATE        INDEX ix_job_posting_municipality      ON job_posting (municipality);
CREATE UNIQUE INDEX ux_job_posting_source_natural    ON job_posting_source (source, source_ad_id);
CREATE        INDEX ix_job_posting_source_posting    ON job_posting_source (job_posting_id);
CREATE UNIQUE INDEX ux_ats_tenant_host               ON ats_tenant (host);
CREATE        INDEX ix_ingest_run_started_at         ON ingest_run (started_at DESC);
