CREATE TABLE cv_document (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    filename       VARCHAR(512) NOT NULL,
    content_type   VARCHAR(128) NOT NULL,
    size_bytes     BIGINT       NOT NULL,
    sha256         VARCHAR(64)  NOT NULL,
    content        BYTEA        NOT NULL,
    extracted_text TEXT,
    uploaded_at    TIMESTAMPTZ  NOT NULL
);

CREATE TABLE cv_profile (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cv_document_id  BIGINT       NOT NULL REFERENCES cv_document (id) ON DELETE CASCADE,
    full_name       VARCHAR(256),
    headline        VARCHAR(512),
    email           VARCHAR(256),
    phone           VARCHAR(64),
    location        VARCHAR(256),
    summary         TEXT,
    language        VARCHAR(8),
    status          VARCHAR(32)  NOT NULL,
    model_used      VARCHAR(64),
    extracted_at    TIMESTAMPTZ,
    reviewed_at     TIMESTAMPTZ
);

CREATE TABLE cv_experience (
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cv_profile_id      BIGINT       NOT NULL REFERENCES cv_profile (id) ON DELETE CASCADE,
    employer           VARCHAR(512),
    title              VARCHAR(512),
    start_date         VARCHAR(32),
    end_date           VARCHAR(32),
    is_current         BOOLEAN      NOT NULL DEFAULT FALSE,
    location           VARCHAR(256),
    ordinal            INTEGER      NOT NULL DEFAULT 0,
    verified           BOOLEAN      NOT NULL DEFAULT TRUE,
    verification_notes TEXT
);

CREATE TABLE cv_experience_bullet (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cv_experience_id BIGINT  NOT NULL REFERENCES cv_experience (id) ON DELETE CASCADE,
    text             TEXT    NOT NULL,
    ordinal          INTEGER NOT NULL DEFAULT 0
);

CREATE TABLE cv_education (
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cv_profile_id      BIGINT       NOT NULL REFERENCES cv_profile (id) ON DELETE CASCADE,
    institution        VARCHAR(512),
    degree             VARCHAR(512),
    field_of_study     VARCHAR(512),
    start_date         VARCHAR(32),
    end_date           VARCHAR(32),
    ordinal            INTEGER      NOT NULL DEFAULT 0,
    verified           BOOLEAN      NOT NULL DEFAULT TRUE,
    verification_notes TEXT
);

CREATE TABLE cv_skill (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cv_profile_id BIGINT       NOT NULL REFERENCES cv_profile (id) ON DELETE CASCADE,
    name          VARCHAR(256) NOT NULL,
    category      VARCHAR(128),
    ordinal       INTEGER      NOT NULL DEFAULT 0
);

CREATE UNIQUE INDEX ux_cv_document_sha256      ON cv_document (sha256);
CREATE        INDEX ix_cv_profile_document     ON cv_profile (cv_document_id);
CREATE        INDEX ix_cv_experience_profile   ON cv_experience (cv_profile_id);
CREATE        INDEX ix_cv_bullet_experience    ON cv_experience_bullet (cv_experience_id);
CREATE        INDEX ix_cv_education_profile    ON cv_education (cv_profile_id);
CREATE        INDEX ix_cv_skill_profile        ON cv_skill (cv_profile_id);
