CREATE TABLE tailored_application (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    job_posting_id    BIGINT      NOT NULL REFERENCES job_posting (id) ON DELETE CASCADE,
    cv_profile_id     BIGINT      NOT NULL REFERENCES cv_profile (id) ON DELETE CASCADE,
    status            VARCHAR(32) NOT NULL,
    model_used        VARCHAR(64),
    coverage_percent  INTEGER     NOT NULL DEFAULT 0,
    generated_at      TIMESTAMPTZ NOT NULL,
    reviewed_at       TIMESTAMPTZ,
    letter_prose      TEXT,
    raw_model_output  TEXT
);

CREATE TABLE application_requirement (
    id                      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tailored_application_id BIGINT  NOT NULL REFERENCES tailored_application (id) ON DELETE CASCADE,
    text                    TEXT    NOT NULL,
    ordinal                 INTEGER NOT NULL DEFAULT 0,
    over_broad              BOOLEAN NOT NULL DEFAULT FALSE
);

CREATE TABLE application_evidence (
    id                         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    application_requirement_id BIGINT NOT NULL REFERENCES application_requirement (id) ON DELETE CASCADE,
    -- Nullable and SET NULL: deleting a CV bullet must not gut past applications.
    cv_experience_bullet_id    BIGINT REFERENCES cv_experience_bullet (id) ON DELETE SET NULL,
    -- The snapshot is what makes an approved application immutable.
    bullet_text                TEXT    NOT NULL,
    ordinal                    INTEGER NOT NULL DEFAULT 0
);

CREATE UNIQUE INDEX ux_tailored_application_job_profile
    ON tailored_application (job_posting_id, cv_profile_id);
CREATE INDEX ix_tailored_application_job     ON tailored_application (job_posting_id);
CREATE INDEX ix_tailored_application_status  ON tailored_application (status);
CREATE INDEX ix_application_requirement_app  ON application_requirement (tailored_application_id);
CREATE INDEX ix_application_evidence_req     ON application_evidence (application_requirement_id);
