-- Slice 2d — job fit triage.
--
-- Table names state their lifecycle, because the lifecycles are opposite:
--   job_prescreen  is truncated and rebuilt on every prescreen run
--   job_deep_fit   costs ~94 seconds per row and must survive
--   job_triage     is your judgement and must survive
-- Nothing preserved may hold a foreign key into job_prescreen.

-- What you will accept. A singleton: things you decide, not things your CV says,
-- so re-extracting a CV can never clobber them.
CREATE TABLE job_preferences (
    id                       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    home_municipality        VARCHAR(128),
    -- Comma-separated plain names, matching search_criteria.municipality_names.
    acceptable_municipalities TEXT,
    remote_policy            VARCHAR(32) NOT NULL DEFAULT 'HYBRID_OK',
    deal_breakers            TEXT,
    updated_at               TIMESTAMPTZ NOT NULL
);

INSERT INTO job_preferences (id, remote_policy, updated_at)
VALUES (1, 'HYBRID_OK', now());

CREATE TABLE candidate_language (
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    job_preferences_id BIGINT      NOT NULL REFERENCES job_preferences (id) ON DELETE CASCADE,
    language           VARCHAR(8)  NOT NULL,
    -- Ordered: NONE < BASIC < CONVERSATIONAL < PROFESSIONAL < FLUENT < NATIVE.
    -- An enum rather than free text because a deterministic gate needs to compare.
    level              VARCHAR(32) NOT NULL,
    ordinal            INTEGER     NOT NULL DEFAULT 0
);

-- DISPOSABLE. Truncated and rebuilt in full by every prescreen run.
CREATE TABLE job_prescreen (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    job_posting_id      BIGINT      NOT NULL REFERENCES job_posting (id) ON DELETE CASCADE,
    -- A stamp recording which profile produced this row, not part of its identity.
    cv_profile_id       BIGINT      NOT NULL REFERENCES cv_profile (id) ON DELETE CASCADE,
    matched_skill_count INTEGER     NOT NULL DEFAULT 0,
    -- Comma-separated skill names, for display. The count is what orders the list.
    matched_skills      TEXT,
    language_gate       VARCHAR(16) NOT NULL,
    -- The phrase from the ad that produced the verdict. A veto always shows its evidence.
    language_note       TEXT,
    location_gate       VARCHAR(16) NOT NULL,
    deadline_passed     BOOLEAN     NOT NULL DEFAULT FALSE,
    computed_at         TIMESTAMPTZ NOT NULL
);

-- PRESERVED. Roughly 94 seconds of local-model time per row.
CREATE TABLE job_deep_fit (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    job_posting_id   BIGINT      NOT NULL REFERENCES job_posting (id) ON DELETE CASCADE,
    cv_profile_id    BIGINT      NOT NULL REFERENCES cv_profile (id) ON DELETE CASCADE,
    coverage_percent INTEGER     NOT NULL DEFAULT 0,
    requirement_count INTEGER    NOT NULL DEFAULT 0,
    model_used       VARCHAR(64),
    deep_scored_at   TIMESTAMPTZ NOT NULL
);

-- PRESERVED. The requirements that matched nothing — the most useful output here.
CREATE TABLE job_deep_fit_gap (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    job_deep_fit_id BIGINT  NOT NULL REFERENCES job_deep_fit (id) ON DELETE CASCADE,
    text            TEXT    NOT NULL,
    ordinal         INTEGER NOT NULL DEFAULT 0
);

-- PRESERVED. Your decision. Never recomputed by anything.
CREATE TABLE job_triage (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    job_posting_id BIGINT      NOT NULL REFERENCES job_posting (id) ON DELETE CASCADE,
    state          VARCHAR(32) NOT NULL,
    decided_at     TIMESTAMPTZ NOT NULL,
    note           TEXT
);

-- 'simple', not 'swedish': a generated column needs an IMMUTABLE expression, so the
-- config cannot depend on the row's language. It is also the right config regardless —
-- skill terms are proper nouns, and stemming mangles Spring and React.
ALTER TABLE job_posting ADD COLUMN search_tsv tsvector
    GENERATED ALWAYS AS (
        to_tsvector('simple', coalesce(title, '') || ' ' || coalesce(description, ''))
    ) STORED;

CREATE INDEX ix_job_posting_search_tsv ON job_posting USING GIN (search_tsv);

CREATE UNIQUE INDEX ux_job_prescreen_job ON job_prescreen (job_posting_id);
CREATE INDEX ix_job_prescreen_matches    ON job_prescreen (matched_skill_count DESC);
CREATE UNIQUE INDEX ux_job_deep_fit_job_profile
    ON job_deep_fit (job_posting_id, cv_profile_id);
CREATE INDEX ix_job_deep_fit_gap_fit     ON job_deep_fit_gap (job_deep_fit_id);
CREATE UNIQUE INDEX ux_job_triage_job    ON job_triage (job_posting_id);
CREATE INDEX ix_candidate_language_prefs ON candidate_language (job_preferences_id);
