-- Slice 2c — the immutable record of an approved application.
--
-- PRESERVED, in the sense Slice 2d established for job_triage: tailored_application is
-- working state that a re-tailor may replace outright, and every approval must still
-- survive that. Hence nullable foreign keys with ON DELETE SET NULL — traceability, never
-- dependency — and its own copy of everything needed to read the row standalone.

CREATE TABLE application_archive (
    id                      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    -- Traceability only. Null once the thing they point at is gone; the row stays readable.
    tailored_application_id BIGINT REFERENCES tailored_application (id) ON DELETE SET NULL,
    job_posting_id          BIGINT REFERENCES job_posting (id)          ON DELETE SET NULL,
    cv_profile_id           BIGINT REFERENCES cv_profile (id)           ON DELETE SET NULL,

    -- The ad, copied. JobMergeService overwrites job_posting.description whenever a richer
    -- version of the same ad is found, and employers delete postings.
    job_title               VARCHAR(512)  NOT NULL,
    employer_name           VARCHAR(512),
    job_canonical_url       VARCHAR(1024),
    -- Stored for the candidate to read. Nothing in this slice dereferences it.
    job_apply_url           VARCHAR(2048),
    job_description_text    TEXT,

    -- The letter as text, for a form field that wants text rather than a file.
    letter_text             TEXT,

    -- bytea, never oid. @Lob maps to oid; Slice 2a settled this on cv_document.content.
    cv_pdf                  BYTEA        NOT NULL,
    cv_pdf_sha256           VARCHAR(64)  NOT NULL,
    letter_pdf              BYTEA        NOT NULL,
    letter_pdf_sha256       VARCHAR(64)  NOT NULL,

    coverage_percent        INTEGER      NOT NULL DEFAULT 0,
    rendered_by             VARCHAR(128),
    approved_at             TIMESTAMPTZ  NOT NULL
);

-- Deliberately NOT unique on tailored_application_id: discarding an approved application and
-- approving a replacement must add a row, not overwrite one.
CREATE INDEX ix_application_archive_approved  ON application_archive (approved_at DESC);
CREATE INDEX ix_application_archive_app       ON application_archive (tailored_application_id);
